### ISSUE TITLE
RFxmit ignores the repeat parameter

### ISSUE THREAD

**Issue by hufman** [atlas0fd00m/rfcat#2]
It looks like the [firmware ](https://github.com/atlas0fd00m/rfcat/blob/master/firmware/appFHSSNIC.c#L834)is ignoring the repeat parameter that rflib sends.
However, when I tried to put it back in, the firmware stopped responding to all commands after finishing the transmission. I tried debugging and couldn't figure out the reason why.
Is there a configuration step that I should run to keep it responding?
Thank you!

**Comment by spaivaras** [comment]
It actually seems that client side should multiple? the buffer before sending it to firmware, (so no need anything with repeat in firmware) https://github.com/atlas0fd00m/rfcat/blob/53b26b41a77b838adfce1b64dadf14083e2dd7d0/rflib/chipcon_nic.py#L1311

But it still seems that repeat option doesn't work as intended (only a single buffer is sent out)

**Comment by hufman** [comment]
I think the InfiniteMode branch is when the firmware stopped using the repeat parameter. The firmware was using it [before merging the branch](https://github.com/atlas0fd00m/rfcat/blob/54282bbbd9ad401de481938817a2b6ae5d3098eb/firmware/appFHSSNIC.c#L645), and stopped [after](https://github.com/atlas0fd00m/rfcat/blob/5d5a666178c11c397a0815c46570dc72d93b7645/firmware/appFHSSNIC.c#L834) the branch was merged.

**Comment by spaivaras** [comment]
I tried to replace 0 with repeat variable in firmware (as its already extracted from 6 bytes python client sends to XMIT function), but now there are timeouts while using repeat function, meaning its more than just passing it. Will dig a bit deeper. Thx for the pointers

**Comment by Sifayne** [comment]
Pretty sure the repeat just repeats the message in the same packet, cause if I print a while received message between 2 dongles with repeat=5 and message="message" the output on the other side is "messagemessagemessagemessagemessage"

**Comment by inode-** [comment]
I can confirm that using latest source code for the firmware there is some problems in repeat and others, after an RFxmit most of the time the chip stop to respond. Code like that one won't work.

```
while x<90:
	d.RFxmit(rf_data)
	x = x+1
```
using the 54282bbbd9ad401de481938817a2b6ae5d3098eb (as told by @hufman) firmware everything seems to work fine.

**Comment by ahobgood** [comment]
Running the latest firmware and rfcat revision, it appears that this issue still exists.  RFxmit() repeats the packet for many seconds, and the dongle fails to respond to any additional commands (requires a re-plug to detect again).

``` 
Traceback (most recent call last):
  File "script.py", line 11, in <module>
    d.RFxmit(bytes.fromhex('888e888e88ee8e8e8888ee8880'))
  File "/usr/local/lib/python2.7/dist-packages/rflib/chipcon_nic.py", line 1331, in RFxmit
    self.send(APP_NIC, NIC_XMIT, "%s" % struct.pack("<HHH",len(data),repeat,offset)+data, wait=wait)
  File "/usr/local/lib/python2.7/dist-packages/rflib/chipcon_usb.py", line 713, in send
    return self.recv(app, cmd, wait)
  File "/usr/local/lib/python2.7/dist-packages/rflib/chipcon_usb.py", line 677, in recv
    raise ChipconUsbTimeoutException
rflib.chipcon_usb.ChipconUsbTimeoutException: Timeout waiting for USB response.
```

Is there any plan to fix this infinite TX bug, or do I have to revert to early-2016 firmware to recover transmit capability?

**Comment by atlas0fd00m** [comment]
@MajorMalfunction can you please look into this bug?  thanks in advance.
