### ISSUE TITLE
error when running rfcat -r

### ISSUE THREAD

**Issue by nocomp** [atlas0fd00m/rfcat#75]
hi folks,
i am trying to cinfigure my ubuntu 18.06 before receiving the dongle,
when i run rfcat -r i get this error:
any idea?
thxx for helping

nocomp@P0wnB0x:~/tools/sdr/rfcat$ rfcat -r
Traceback (most recent call last):
  File "/usr/local/bin/rfcat", line 11, in <module>
    from rflib import *
  File "/usr/local/lib/python3.6/dist-packages/rflib/__init__.py", line 240
    except ImportError, e:
                      ^
SyntaxError: invalid syntax
nocomp@P0wnB0x:~/tools/sdr/rfcat$ sudo rfcat -r
Traceback (most recent call last):
  File "/usr/local/bin/rfcat", line 11, in <module>
    from rflib import *
  File "/usr/local/lib/python3.6/dist-packages/rflib/__init__.py", line 240
    except ImportError, e:
                      ^
SyntaxError: invalid syntax
nocomp@P0wnB0x:~/tools/sdr/rfcat$

**Comment by LalaDK** [comment]
I had trouble running RFCat on Ubuntu 20.04 with Python3. 
I managed to install Python2 and I got it working flawlessly!

**Comment by atlas0fd00m** [comment]
hello @LalaDK , can you explain your issues with Python3 and RfCat?  we'd certainly like to get them all fixed if possible.  we have an upcoming version release that is dependent upon the quality of the Py3 experience.

thanks!
@
