### ISSUE TITLE
install to ubuntu peppermint

### ISSUE THREAD

**Issue by maaxxyy** [atlas0fd00m/rfcat#92]
Hi guys i,m having a few issues trying to install it to my ubuntu peppermint  mini laptop. Below is the issues i am having - 

Traceback (most recent call last):
  File "/usr/local/bin/rfcat", line 4, in <module>
    __import__('pkg_resources').run_script('rfcat==1.9.3', 'rfcat')
  File "/home/eee/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/home/eee/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/eee/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/eee/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/eee/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/eee/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'future' distribution was not found and is required by rfcat

Any help would be  appreciated thanks

**Comment by atlas0fd00m** [comment]
i'm afraid i'm unfamiliar with Ubuntu Perppermint 10 Bubonic.

the problem appears to be with the "future" tools 
have you pip installed the requirements.txt?

first you need python2 pip.  if you don't, lookup a way to install it for your version of linux.  it must be pip for python2, not python3.

next, type the following from within the rfcat directory:
`$ pip install -r requirements.txt`

**Comment by maaxxyy** [comment]
Thanks for the reply, here is what i found -

root@eeepc /home/eee/rfcat # rfcat -r
Traceback (most recent call last):
  File "/usr/local/bin/rfcat", line 4, in <module>
    __import__('pkg_resources').run_script('rfcat==1.9.3', 'rfcat')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PySide2' distribution was not found and is required by rfcat
root@eeepc /home/eee/rfcat # pip install -r requirements.txt
Collecting PySide2 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement PySide2 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for PySide2 (from -r requirements.txt (line 1))
root@eeepc /home/eee/rfcat #

**Comment by maaxxyy** [comment]
Theres still an issue with pyside2, done exactly the same with my raspberry pi 3 b+ running the newest buster os and the older rasbian. This is frustrating as i cant use   
my YS1.

**Comment by atlas0fd00m** [comment]
hmmmm...  i could potentially remove PySide2 from requirements.txt, which would allow it to install via pip...
the GUI is only for running the specan.

would that benefit you?

**Comment by oosfoos** [comment]
> 
> 
> hmmmm... i could potentially remove PySide2 from requirements.txt, which would allow it to install via pip...
> the GUI is only for running the specan.
> 
> would that benefit you?

I think that's probably a good way to go, at least until PySide2 is ready to go for ARM, I spent way too long trying to get rfcat to install properly on my rpi because of this.

**Comment by atlas0fd00m** [comment]
check now
